ALTER TABLE "ServiceItem" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "ServiceItem" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "GalleryItem" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "GalleryItem" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "Testimonial" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Testimonial" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "FAQItem" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "FAQItem" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "ProductSliderItem" ADD COLUMN "isActive" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "ProductSliderItem" ADD COLUMN "order" INTEGER NOT NULL DEFAULT 0;
